name: Build Docker image

on: [push, pull_request]

jobs:
    build:
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v4
        - name: Run and test docker
          run: |
            docker build .
    
    release:
      needs:
        - build
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Release
          run: |
            npm install
            npx semantic-release --branches main
          env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
        - name: Log in to Docker Hub
          uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
    
        - name: Retrieve version
          id: tag
          run: echo "version=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
    
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
          with:
            images: ${{ secrets.DOCKER_IMAGENAME }}
            tags: |
              ${{ steps.tag.outputs.version }}
              latest
    
        - name: Build and push Docker image
          uses: docker/build-push-action@2a7db1d68aab1a514ba647f39bcde60888a1753f
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
